server:
  port: 8081

spring:
  application:
    name: profile

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: crnb001
    password: rnb6707
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
logging:
  level:
    org.hibernate.sql: DEBUG            # Hibernate가 생성하는 SQL 쿼리 레벨을 DEBUG로 설정
    org.hibernate.orm.jdbc.bind: TRACE  # SQL 쿼리 파라미터 바인딩 값 출력 (DEBUG보다 더 상세)
    com.rnbsoft.profile: DEBUG          # 당신의 애플리케이션 패키지 로그 레벨 설정

jwt:
  # JWT (JSON Web Token)은 클라이언트와 서버 간에 정보를 안전하게 주고받기 위한 경량의 인증 방식입니다.
  # secret: 토큰을 서명하고 검증하는 데 사용되는 비밀 키입니다. 이 키는 외부에 노출되어서는 안 됩니다.
  #         토큰의 무결성을 보장하고, 위변조 여부를 확인할 수 있도록 해주는 핵심 요소입니다.
  #         최소 32바이트(256비트) 이상의 길이를 가지는 안전한 임의의 문자열을 Base64로 인코딩하여 사용해야 합니다.
  #         없으면 토큰을 생성하거나 검증할 수 없습니다. 아래 방법을 참고하여 생성 후 여기에 붙여넣으세요.
  secret-key: xmccQLOogu0UoxGPk8TUSZDMRk0J/ucMiFyxih9h7Yw= # 이 값을 실제 시크릿 키로 변경하세요!
  # expiration-time: 토큰의 유효 기간을 밀리초(ms) 단위로 설정합니다. (예: 3600000ms = 1시간)
  #                  토큰이 이 시간보다 오래되면 만료되어 더 이상 유효하지 않게 됩니다.
  expiration-time: 3600000 # 1시간 (밀리초)